In [94]:
!pip install openpyxl xlrd

Requirement already satisfied: openpyxl in c:\programdata\anaconda3\lib\site-packages (3.0.7)
Requirement already satisfied: xlrd in c:\programdata\anaconda3\lib\site-packages (2.0.1)
Requirement already satisfied: et-xmlfile in c:\programdata\anaconda3\lib\site-packages (from openpyxl) (1.0.1)

In [95]:
import pandas as pd
url = "https://www.sharkattackfile.net/spreadsheets/GSAF5.xls"
df = pd.read_excel(url)
df.head(3)

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,15 Mar 2024,2024.0,Unprovoked,AUSTRALIA,Queensland,Bargara Beach,Swimming,Brooklyn Sauer,F,13,...,Tiger shark,"Yahoo News, 3/15/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,04 Mar 2024,2024.0,Unprovoked,USA,Hawaii,"Old Man's, Waikiki",Surfing,Matthew White,M,NaN,...,Tiger shark 8',"Surfer, 3/6/2024F",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,02 Mar-2024,2024.0,Unprovoked,USA,Hawaii,"Rainbows, Oahu",Swimming,NaN,F,11,...,3' to 4' shark,"Hawaii News Now, 3/4/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
df.shape

(6969, 23)

In [97]:
df.dtypes

Date               object
Year              float64
Type               object
Country            object
State              object
Location           object
Activity           object
Name               object
Sex                object
Age                object
Injury             object
Unnamed: 11        object
Time               object
Species            object
Source             object
pdf                object
href formula       object
href               object
Case Number        object
Case Number.1      object
original order    float64
Unnamed: 21        object
Unnamed: 22        object
dtype: object

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6969 entries, 0 to 6968
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            6944 non-null   object
 1   Year            6942 non-null   float64
 2   Type            6926 non-null   object
 3   Country         6894 non-null   object
 4   State           6462 non-null   object
 5   Location        6379 non-null   object
 6   Activity        6358 non-null   object
 7   Name            6724 non-null   object
 8   Sex             6365 non-null   object
 9   Age             3950 non-null   object
 10  Injury          6909 non-null   object
 11  Unnamed: 11     6382 non-null   object
 12  Time            3418 non-null   object
 13  Species         3812 non-null   object
 14  Source          6925 non-null   object
 15  pdf             6799 non-null   object
 16  href formula    6819 non-null   object
 17  href            6796 non-null   object
 18  Case Number     6798 non-null   object
 19  Case Number.1   6797 non-null   object
 20  original order  6799 non-null   float64
 21  Unnamed: 21     1 non-null      object
 22  Unnamed: 22     2 non-null      object
dtypes: float64(2), object(21)
memory usage: 1.2+ MB

In [99]:
df.isnull().sum()

Date                25
Year                27
Type                43
Country             75
State              507
Location           590
Activity           611
Name               245
Sex                604
Age               3019
Injury              60
Unnamed: 11        587
Time              3551
Species           3157
Source              44
pdf                170
href formula       150
href               173
Case Number        171
Case Number.1      172
original order     170
Unnamed: 21       6968
Unnamed: 22       6967
dtype: int64

In [100]:
df["href formula"].value_counts()

http://sharkattackfile.net/spreadsheets/pdf_directory/                                       25
http://sharkattackfile.net/spreadsheets/pdf_directory/1934.12.23.a-b-Inman.pdf                2
http://sharkattackfile.net/spreadsheets/pdf_directory/1916.07.12.a-b-Stillwell-Fisher.pdf     2
http://sharkattackfile.net/spreadsheets/pdf_directory/1931.09.21.a-b-Holaday-Barrows.pdf      2
http://sharkattackfile.net/spreadsheets/pdf_directory/1929.03.04.a-b.Roads-Aldridge.pdf       2
                                                                                             ..
http://sharkattackfile.net/spreadsheets/pdf_directory/1938.07.17-Griffet.pdf                  1
http://sharkattackfile.net/spreadsheets/pdf_directory/2006.12.10-Frailey.pdf                  1
http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0053-India.pdf                       1
http://sharkattackfile.net/spreadsheets/pdf_directory/1990.10.20-Demers.pdf                   1
http://sharkattackfile.net/spreadsheets/pdf_directory/1945.09.19-Bemis.pdf                    1
Name: href formula, Length: 6785, dtype: int64

In [101]:
#Eliminacion de columnas sin valor informativa
df = df.iloc[:, :15]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6969 entries, 0 to 6968
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         6944 non-null   object
 1   Year         6942 non-null   float64
 2   Type         6926 non-null   object
 3   Country      6894 non-null   object
 4   State        6462 non-null   object
 5   Location     6379 non-null   object
 6   Activity     6358 non-null   object
 7   Name         6724 non-null   object
 8   Sex          6365 non-null   object
 9   Age          3950 non-null   object
 10  Injury       6909 non-null   object
 11  Unnamed: 11  6382 non-null   object
 12  Time         3418 non-null   object
 13  Species      3812 non-null   object
 14  Source       6925 non-null   object
dtypes: float64(1), object(14)
memory usage: 816.8+ KB

In [102]:
df.columns = df.columns.str.lower()
df.rename(columns = {"unnamed: 11":"fatality"}, inplace = True)

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6969 entries, 0 to 6968
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      6944 non-null   object
 1   year      6942 non-null   float64
 2   type      6926 non-null   object
 3   country   6894 non-null   object
 4   state     6462 non-null   object
 5   location  6379 non-null   object
 6   activity  6358 non-null   object
 7   name      6724 non-null   object
 8   sex       6365 non-null   object
 9   age       3950 non-null   object
 10  injury    6909 non-null   object
 11  fatality  6382 non-null   object
 12  time      3418 non-null   object
 13  species   3812 non-null   object
 14  source    6925 non-null   object
dtypes: float64(1), object(14)
memory usage: 816.8+ KB

In [104]:
df[df.duplicated()]

,date,year,type,country,state,location,activity,name,sex,age,injury,fatality,time,species,source
5318,Fall 1943,1943.0,Unprovoked,USA,Hawaii,"Midway Island, Northwestern Hawaiian Islands",Spearfishing,2 males,M,NaN,Calf nipped in each case,N,NaN,"""small sharks""",W. M. Chapman
6945,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6947,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6949,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6951,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6952,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6953,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6954,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6955,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6957,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6958,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6959,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6966,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6967,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [105]:
df = df.drop_duplicates()

In [106]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6944 entries, 0 to 6944
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      6943 non-null   object
 1   year      6941 non-null   float64
 2   type      6925 non-null   object
 3   country   6893 non-null   object
 4   state     6461 non-null   object
 5   location  6378 non-null   object
 6   activity  6357 non-null   object
 7   name      6723 non-null   object
 8   sex       6364 non-null   object
 9   age       3950 non-null   object
 10  injury    6908 non-null   object
 11  fatality  6381 non-null   object
 12  time      3418 non-null   object
 13  species   3811 non-null   object
 14  source    6924 non-null   object
dtypes: float64(1), object(14)
memory usage: 868.0+ KB

(6944, 15)

In [107]:
df["type"].value_counts()

Unprovoked             5106
Provoked                635
Invalid                 552
Watercraft              355
Sea Disaster            242
Questionable             22
Boat                      7
 Provoked                 2
?                         1
Under investigation       1
Unconfirmed               1
Unverified                1
Name: type, dtype: int64

In [108]:
type_mapping = {
"Invalid": "Under investigation",
"Boat": "Watercraft",
" Provoked" : "Provoked",
"?": "Under investigation",
"Unconfirmed":"Under investigation",
"Unverified":"Under investigation",
"Questionable":"Under investigation"
}

df["type"] = df["type"].replace(type_mapping)
df["type"].value_counts()

Unprovoked             5106
Provoked                637
Under investigation     578
Watercraft              362
Sea Disaster            242
Name: type, dtype: int64

In [109]:
df["country"].value_counts()[df["country"].value_counts() > 30]

USA                 2537
AUSTRALIA           1481
SOUTH AFRICA         597
NEW ZEALAND          144
BAHAMAS              136
PAPUA NEW GUINEA     136
BRAZIL               122
MEXICO               103
ITALY                 72
FIJI                  67
NEW CALEDONIA         65
PHILIPPINES           63
REUNION               60
EGYPT                 49
CUBA                  49
MOZAMBIQUE            46
SPAIN                 46
INDIA                 41
FRENCH POLYNESIA      37
JAPAN                 36
CROATIA               35
PANAMA                32
Name: country, dtype: int64

In [110]:
# Paso 1: Contar las apariciones de cada valor Ãºnico en la columna
conteo_valores = df["country"].value_counts()

# Paso 2: Filtrar los valores que aparecen mÃ¡s veces que el nÃºmero deseado (por ejemplo, 5 veces)
valores_frecuentes = conteo_valores[conteo_valores > 30].index

# Paso 3: Filtrar las filas del DataFrame original donde la columna contiene esos valores
df = df[df["country"].isin(valores_frecuentes)]

In [111]:
df["country"] = df["country"].str.replace("REUNION","REUNION ISLAND")

In [117]:
df["country"].value_counts()

USA                 2537
AUSTRALIA           1481
SOUTH AFRICA         597
NEW ZEALAND          144
BAHAMAS              136
PAPUA NEW GUINEA     136
BRAZIL               122
MEXICO               103
ITALY                 72
FIJI                  67
NEW CALEDONIA         65
PHILIPPINES           63
REUNION ISLAND        60
CUBA                  49
EGYPT                 49
SPAIN                 46
MOZAMBIQUE            46
INDIA                 41
FRENCH POLYNESIA      37
JAPAN                 36
CROATIA               35
PANAMA                32
Name: country, dtype: int64

In [113]:
#df[df['country'].str.contains(r'REUNION', na=False)]

,date,year,type,country,state,location,activity,name,sex,age,injury,fatality,time,species,source
741,18-Jun-2017,2017.0,Unprovoked,REUNION ISLAND,NaN,Roches Noire,Body boarding,Julien,M,34,"No injury, shark bit surfboard",N,10h00,"Bull shark, 2m","Clincanoo, 6/19/2017"
761,29-Apr-2017,2017.0,Unprovoked,REUNION ISLAND,Saint-Leu,Pointe au Sal,Body boarding,Adrien Dubosc,M,28,FATAL,Y,11h15,NaN,"Clicanoo, 4/29/2017"
788,21-Feb-2017,2017.0,Unprovoked,REUNION ISLAND,Saint-Andre,NaN,Body boarding,Alexandre Naussance,M,26,Fatal,Y,09h30,NaN,"Surfline, 2/21/2017"
843,27-Aug-2016,2016.0,Unprovoked,REUNION ISLAND,NaN,Boucan Canot,Surfing,Laurent Chardard,M,20,"Right arm severed, ankle severely bitten",N,17h00,"Bull shark, 3.5 m","LaDepeche, 8/29/2016"
1003,22-Jul-2015,2015.0,Unprovoked,REUNION ISLAND,NaN,St. Leu,Surfing,Rodolphe ArriÃ©guy,M,45,Arm bitten,N,NaN,"Bull shark, 2m",Zig Zag Surfing Magazine
1033,01-Jun-2015,2015.0,Unprovoked,REUNION ISLAND,Le Port,Folette,Surfing,Eddy Chaussalet,M,47,Left forearm bitten,N,15h00,"Bull shark, 2.5 m","Clincanoo, 6/1/2015"
1049,12-Apr-2015,2015.0,Unprovoked,REUNION ISLAND,Saint-Gilles-les-Bains,Cap Homard,Surfing,Elio Canestri,M,13,FATAL,Y,09h00,Bull shark,"Le Huffington Post, 4/15/2015"
1062,14-Feb-2015,2015.0,Unprovoked,REUNION ISLAND,dâ€™Ã‰tang-SalÃ©,Ravine Mula,Swimming,Talon Bishop,F,22,FATAL,Y,18h30,"Tiger shark, 3.5 m","L'Yonne RÃ©publicaine, 2/14/2015"
1141,22-Jul-2014,2014.0,Unprovoked,REUNION ISLAND,Saint-Leu,NaN,Surfing,Vincent Rintz,M,51,Lacerations to right wrist & calf,N,15h00,1.8 metre shark,"BFM-tv, 7/22/2014"
1221,26-Oct-2013,2013.0,Unprovoked,REUNION ISLAND,dâ€™Ã‰tang-SalÃ©,Ravine Mula,Body boarding,Gicquel Tanguy,M,24,Right leg severed,N,16h30,Thought to involve a bull shark,"Global Post, 10/26/2013"
1268,15-Jul-2013,2013.0,Unprovoked,REUNION ISLAND,Saint-Paul,Le cimetiÃ¨re marin,Swimming & snorkeling,Sarah Roperh,F,15,FATAL,Y,14h15,NaN,"Clicanoo, 7/15/2013"
1291,08-May-2013,2013.0,Unprovoked,REUNION ISLAND,Saint-Gilles,Brisant Beach,Body boarding,StÃ©phane Berhamel,M,36,FATAL,Y,08h20,Bull shark,A. Morel
1369,06-Aug-2012,2012.0,Unprovoked,REUNION ISLAND,Saint Leu,NaN,Surfing,Fabien Bujon,M,39,Right hand and foot severed,N,17h17,Bull shark,"Linfo.re, 8/5/2012"
1376,23-Jul-2012,2012.0,Unprovoked,REUNION ISLAND,Trois-Bassins,NaN,Surfing,Alexandre Rassiga,M,22,FATAL,Y,16h30,NaN,"Clicanoo.re, 7/23/20122"
1426,05-Mar-2012,2012.0,Unprovoked,REUNION ISLAND,Saint-Benoit,Port de laÂ Marine,Body boarding,Gerard Itema,M,31,"No injury, board bitten",N,14h30,NaN,"Clicanoo, 3/5/2012"
1460,11-Nov-2011,2011.0,Unprovoked,REUNION ISLAND,Bois-Blanc,Sainte-Rose,Free diving / spearfishing,Jean-Paul Delaunay,M,42,Left foot bitten,N,Morning,NaN,"H. Nickel & A. Brenneka, SharkAttackSurvivors.com"
1470,05-Oct-2011,2011.0,Watercraft,REUNION ISLAND,NaN,Cap La Houssaye,Canoeing,Jean-Pierre Castellani,M,51,No injury to occupant,N,10h30,2 to 2.5 m shark,"Clicanoo, 10/5/2011"
1479,19-Sep-2011,2011.0,Unprovoked,REUNION ISLAND,Saint-Gilles,Boucan-Canot,Body boarding,Mathieu Schiller,M,38,FATAL,Y,15h30,NaN,zinfos974
1509,15-Jul-2011,2011.0,Watercraft,REUNION ISLAND,Saint-Gilles,Brisants.,Kayaking or Wave skiing,male,M,NaN,No injury,N,17h00,NaN,"Le Post, 7/19/2011"
1514,06-Jul-2011,2011.0,Unprovoked,REUNION ISLAND,Saint-Gilles,Roches Noires,Surfing,Arnaud Dussel,M,16,Minor injuries: scratches on nose & ankle. Boa...,N,14h50,NaN,"V. Boyer, Le Journal de lâ€™Ã®le de la RÃ©union, 7..."
1524,15-Jun-2011,2011.0,Unprovoked,REUNION ISLAND,Saint-Gilles-les-Bains,Boucan-Canot,Boogie Boarding,Eddie Aubert,M,31,FATAL,Y,17h30,NaN,"Surfprevention.com, 6/16/2011"
1558,18-Feb-2011,2011.0,Unprovoked,REUNION ISLAND,Saint Gilles,Trois-Roches,Surfing,Eric Dargent,M,32,Left leg severed at the knee,N,18h30,NaN,"Clicanoo.com, 2/21/2011"
1649,27-Mar-2010,2010.0,Unprovoked,REUNION ISLAND,Saint-Benoit,Bittern,Surfing,Oliver Schorebreak,M,34,"No injury, board bitten",N,11h00,1.5 m shark,"C. Ekstander, GSAF"
1979,04-Jul-2007,2007.0,Unprovoked,REUNION ISLAND,NaN,Boucan Canot,Body boarding,Vincent Bouju,M,17,Minor injuries to thigh & knee,N,14h30,2 m shark,"clicanoo.com, 7/5/2007"
2055,27-Aug-2006,2006.0,Unprovoked,REUNION ISLAND,Saint-Gilles-les-Bains,"Les Aigrettes, near Boucan-Canot",Body boarding,GÃ©rald PrÃ©au,M,27,Laceration to right calf & heel,N,18h00,NaN,"G. Vitry; G. Holt, scubaradio; Clicanoo, 8/28/..."
2059,20-Aug-2006,2006.0,Unprovoked,REUNION ISLAND,Saint-Pierre,Pointe du Diable,Surfing,SÃ©bastien Ã‰mond,M,34,FATAL,Y,11h00,NaN,P. Immerz
2063,Early Aug-2006,2006.0,Unprovoked,REUNION ISLAND,NaN,Le Port,Spearfishing,male,M,NaN,Thigh bitten,N,NaN,"Bull shark, 1.5m","Clicanoo, 8/29/2006"
2249,06-Oct-2004,2004.0,Unprovoked,REUNION ISLAND,ConservatÃ³ria District,"P' tit Paris, Saint-Pierre",Body boarding,Vincent Motais,M,15,"Leg severely bitten, surgically amputated",N,16h15,Thought to involve a 2.5 m bull or tiger shark,Federation Francaise de Surf
2302,27-Mar-2004,2004.0,Unprovoked,REUNION ISLAND,Saint-BenoÃ®t,Spot de la gare,Surfing,RÃ©my Lorion,M,20,Right thigh bitten,N,17h00 or 17h40,2.5 m shark,"Clicanoo, le journal de l'Ile de la RÃ©union"
2631,08-Sep-2000,2000.0,Unprovoked,REUNION ISLAND,Saint-Pierre,Pic du Diable,Surfing,Karim Maan,M,27,Left arm bitten,N,18h05,"Tiger shark, 3 m [10']","Clicanoo, le journal de l'Ile de la RÃ©union; ..."
2691,Reported 28-Jan-2000,2000.0,Watercraft,REUNION ISLAND,NaN,Saint Pierre,Canoe with 3 men onboard sank,BoulabhaÃ¯ Ishmael,M,NaN,FATAL,Y,NaN,NaN,B.L. du Vendre
2741,11-Apr-1999,1999.0,Unprovoked,REUNION ISLAND,L' Etang SalÃ©-les-Bains,Roche-aux-Oiseaux,Swimming after being swept into sea by a large...,Guy Oudin,M,52,FATAL,Y,10h30,3 bull sharks,G. Van Grevelynghe
2757,03-Jan-1999,1999.0,Unprovoked,REUNION ISLAND,Saint-Leu,Pointe au Sel,Spearfishing,NaN,NaN,NaN,FATAL,Y,NaN,Bull shark,G. Van Grevelynghe
2775,01-Oct-1998,1998.0,Unprovoked,REUNION ISLAND,Saint-BenoÃ®t,NaN,Diving,NaN,NaN,NaN,Survived,N,NaN,NaN,G. Van Grevelynghe
2818,25-Jan-1998,1998.0,Unprovoked,REUNION ISLAND,Grand'Anse,NaN,Bathing,Philippe Blu,M,NaN,FATAL,Y,Mid afternoon,NaN,G. Van Grevelynghe
2823,1998,1998.0,Unprovoked,REUNION ISLAND,Beaufonds,NaN,Diving,NaN,NaN,NaN,FATAL,Y,NaN,NaN,G. Van Grevelynghe
2876,20-Feb-1997,1997.0,Unprovoked,REUNION ISLAND,L'Etang-Sale,NaN,NaN,Laurent Lebon,M,NaN,Hand injured,N,NaN,NaN,"LeQuotidien, 12/4/1999"
2880,03-Jan-1997,1997.0,Unprovoked,REUNION ISLAND,NaN,la Pointe-au-Sel,Spearfishing,David Lonne,M,NaN,FATAL,Y,NaN,Bull shark,"Clicanoo, le journal de l'Ile de la RÃ©union"
2940,10-Jan-1996,1996.0,Unprovoked,REUNION ISLAND,Saint-Paul,Embouchure de l'Ã©tang de Saint Paul,Surfing,GrÃ©gory BÃ©nÃ¨che,M,25,FATAL,Y,16h00,"Tiger shark, 300-kg [662-lb]","Clicanoo, le journal de l'Ile de la RÃ©union"
2957,16-Sep-1995,1995.0,Unprovoked,REUNION ISLAND,Saint-Denis,NaN,Body-boarding,Jerome Pruneaux,M,NaN,FATAL,Y,NaN,NaN,"LeQuotidien, 12/4/1999"
3043,09-Jul-1994,1994.0,Unprovoked,REUNION ISLAND,Saint-Denis,Barachois,Windsurfing,Thierry Boulay,M,24,FATAL,Y,13h45,3 to 3.5 m [10' to 11.5'] bull shark,G. Van Grevelynghe
3056,15-Apr-1994,1994.0,Unprovoked,REUNION ISLAND,Saint-Joseph,Lieu-dit Cayenne,NaN,NaN,NaN,NaN,FATAL,Y,NaN,"3 m [10'], 200-kg [441-lb] bull shark",G. Van Grevelynghe
3105,29-Jun-1993,1993.0,Unprovoked,REUNION ISLAND,Saint-Paul,Cap de la Marianne,Body boarding,Theirry Mercredi,M,16,Note: see 1992.06.28,N,NaN,NaN,"Quotidien, 4/12/1999"
3164,28-Jun-1992,1992.0,Unprovoked,REUNION ISLAND,Saint-Paul,Cap de la Marianne,Surfing,Theirry Mercredi,M,16,FATAL,Y,14h30,Bull shark or lemon shark,G. Van Grevelynghe
3167,Jun-1992,1992.0,Unprovoked,REUNION ISLAND,Saint-Paul,NaN,Diving,NaN,NaN,NaN,Survived,N,NaN,Mako shark,G. Van Grevelynghe
3169,22-May-1992,1992.0,Unprovoked,REUNION ISLAND,Saint-Joseph,Lieu-dit Cayenne,Surfing,Emmanuel Nativel,M,NaN,FATAL,Y,14h00,"Tiger shark, 3 m to 4 m [10' to 13']",G. Van Grevelynghe
3181,29-Jan-1992,1992.0,Unprovoked,REUNION ISLAND,La Saline-les-Bains,Revine-3-Bassins,Spearfishing,Richard Carnoy,M,NaN,Survived,N,16h30,1.8 m grey shark,G. Van Grevelynghe
3208,01-Jul-1991,1991.0,Unprovoked,REUNION ISLAND,L'Etang-SalÃ©,"Ravine des Sables, Saint Leu",Surfing,Alain Curco-LlovÃ©ra,M,30,Left arm severed,N,17h30,"Tiger shark, 3 to 4 m [10' to 13']","R.D. Weeks, GSAF, p.303; G. Van Grevelynghe"
3262,05-Mar-1990,1990.0,Unprovoked,REUNION ISLAND,Sainte-Marie,Baie de la Mare,Surfing,Wagner Cataldo-Beugleu,M,NaN,Survived,N,17h45,3 m [10'] bull shark,G. Van Grevelynghe
3294,19-Jul-1989,1989.0,Unprovoked,REUNION ISLAND,Sainte-Suzanne,Temple Tamoule,Surfing,Bruno Giraud,M,NaN,FATAL,Y,17h00 Sunset,NaN,"Clicanoo, le journal de l'Ile de la RÃ©union"
3355,28-Apr-1988,1988.0,Unprovoked,REUNION ISLAND,Saint-Louis,Embouchure de l'Ã©tang du Gol,pÃªcheur de bichiques,Jean-Felix Taochyn,M,NaN,FATAL,Y,17h30,NaN,G. Van Grevelynghe
3365,14-Mar-1988,1988.0,Unprovoked,REUNION ISLAND,Saint-Pierre,Pic du Diable,Surfing,FrÃ©dÃ©ric Mousseau,M,NaN,Laceration to hand,N,18h30 (Sunset),NaN,G. Van Grevelynghe
3623,30-Nov-1981,1981.0,Unprovoked,REUNION ISLAND,Saint-Philippe,Vicendo,Spearfishing,Lucien Mercier,M,NaN,Survived,N,Late afternoon,NaN,G. Van Grevelynghe
3671,24-Nov-1980,1980.0,Unprovoked,REUNION ISLAND,Grand'Anse,Petite-Ile,Spearfishing,Jean-Michel Pothin,M,22,Bitten twice,N,15h00,1.8 m [6'] white shark,G. Van Grevelynghe
3869,1975,1975.0,Unprovoked,REUNION ISLAND,NaN,NaN,NaN,a soldier,M,NaN,FATAL,Y,NaN,NaN,Reunion Marine Observatory
3942,01-Dec-1972,1972.0,Unprovoked,REUNION ISLAND,Saint-Philippe,Basse VallÃ©e,Spearfishing,NaN,NaN,NaN,FATAL,Y,NaN,NaN,G. Van Grevelynghe
5995,1913,1913.0,Unprovoked,REUNION ISLAND,Saint-Denis,Barachoise bridge,Swimming after his hat,male,M,NaN,FATAL,Y,NaN,NaN,H. Cornu
5996,1913,1913.0,Unprovoked,REUNION ISLAND,5aint-Denis,Barachois,Swimming,male,M,NaN,FATAL,Y,NaN,NaN,H. Cornu
6860,No date,0.0,Unprovoked,REUNION ISLAND,Grand'Anse,Petite-Ã®le,yachtsman in a zodiac,NaN,M,NaN,Survived,N,NaN,NaN,G. Van Grevelynghe
6920,Between 1918 & 1939,0.0,Unprovoked,REUNION ISLAND,Saint-Denis,Barachois,Swimming,NaN,NaN,NaN,FATAL,Y,NaN,NaN,G. Van Grevelynghe

In [114]:
df["country"]== "ASIA?"

0       False
1       False
2       False
3       False
4       False
        ...
6938    False
6939    False
6940    False
6941    False
6942    False
Name: country, Length: 5954, dtype: bool

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6969 entries, 0 to 6968
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      6944 non-null   object
 1   year      6942 non-null   float64
 2   type      6926 non-null   object
 3   country   6894 non-null   object
 4   state     6462 non-null   object
 5   location  6379 non-null   object
 6   activity  6358 non-null   object
 7   name      6724 non-null   object
 8   sex       6365 non-null   object
 9   age       3950 non-null   object
 10  injury    6909 non-null   object
 11  fatality  6382 non-null   object
 12  time      3418 non-null   object
 13  species   3812 non-null   object
 14  source    6925 non-null   object
dtypes: float64(1), object(14)
memory usage: 816.8+ KB

In [ ]:
#variable de importacia
#date, year, type,country, state, location,activity...time,fatality

In [ ]:
# agencia de turismo extremo
# hypotheses: luagar con mayor ataques, tipo de tiburon que mas ataca, condiciones metereologicas, horarios, actividades.